const lang = {
    en : {
        headerWelcome : "Welcome",
        signIn : "Sign In",
        signUp : "Sign Up",
        home: "Home",
        signOut : "Sign Out",
        name: "Name",
        email: "Email Address",
        password: "Password",
        confirmPassword: "Confirm Password",
        offlineheadind01: "Your System is Offline !",
        offlineheadind02: "Please Check the Internet Connection.",
        nowPlaying: "Now Playing",
        popular: "Popular",
        topRated : "Top Rated",
        upcoming: "Upcoming",
        play: "Play",
        gptSearch : "GPT Search",
        gptSearchHeadind01 : "Let GPT be your movie genie, uncovering the perfect film just for you!",
        gptSearchHeadind02 : "Empower your movie choices with GPT's AI-driven recommendations Now.",
        search : "Search",
        gptSearchBarPlaceHolder : "What whould you like to watch today ?",
    },
    hi : {
        headerWelcome : "स्वागत",
        signIn : "दाखिल करें",
        signUp : "साइन अप करें",
        home: "मुखपृष्ठ",
        signOut : "साइन आउट",
        name: "नाम",
        email: "मेल पता",
        password: "पासवर्ड",
        confirmPassword: "पासवर्ड की पुष्टि कीजिये",
        offlineheadind01: "आपका सिस्टम ऑफ़लाइन है !",
        offlineheadind02: "कृपया इंटरनेट कनेक्शन जांचें.",
        nowPlaying: "अभी चल रही फिल्में",
        popular: "लोकप्रिय",
        topRated : "टॉप रेटेड",
        upcoming: "आगामी",
        play: "चलाएं",
        gptSearch : "जीपीटी खोज",
        gptSearchHeadind01 : "जीपीटी को अपनी फिल्म का जिन्न बनने दें, जो आपके लिए बिल्कुल सही फिल्म की खोज कर रहा है!",
        gptSearchHeadind02 : "अभी GPT की AI-संचालित अनुशंसाओं के साथ अपनी मूवी पसंद को सशक्त बनाएं।",
        search : "खोजे",
        gptSearchBarPlaceHolder : "आज आप क्या देखना पसंद करेंगे?",
    },
    ja : {
        headerWelcome : "いらっしゃいませ",
        signIn : "サインイン",
        signUp : "サインアップ",
        home: "ホームページ",
        signOut : "サインアウト",
        name: "名前",
        email: "電子メールアドレス",
        password: "パスワード",
        confirmPassword: "パスワードを認証する",
        offlineheadind01: "システムはオフラインです !",
        offlineheadind02: "インターネット接続を確認してください。",
        nowPlaying: "映画を再生中",
        popular: "人気のある",
        topRated : "トップレート",
        upcoming: "今後の予定",
        play: "動画を再生します",
        gptSearch : "GPT 検索",
        gptSearchHeadind01 : "GPT をあなたの映画魔神にして、あなたにぴったりの映画を見つけてください !",
        gptSearchHeadind02 : "GPT の AI 主導のレコメンデーションで映画の選択を強化しましょう。",
        search : "検索",
        gptSearchBarPlaceHolder : "今日は何を見たいですか?",
    },
    es : {
        headerWelcome : "bienvenido",
        signIn : "Iniciar sesión",
        signUp : "Inscribirse",
        home: "Página principal",
        signOut : "Desconect",
        name: "Nombre",
        email: "Dirección de correo electrónico",
        password: "Contraseña",
        confirmPassword: "confirmar Contraseña",
        offlineheadind01: "¡Su sistema está fuera de línea!",
        offlineheadind02: "Por favor verifique la conexión a Internet.",
        nowPlaying: "Ahora reproduciendo películas",
        popular: "Popular",
        topRated : "Los más valorados",
        upcoming: "Próximo",
        play: "Reproduce el video",
        gptSearch : "Búsqueda GPT",
        gptSearchHeadind01 : "¡Deja que GPT sea tu genio del cine y descubre la película perfecta solo para ti!",
        gptSearchHeadind02 : "Mejore sus opciones de películas con las recomendaciones basadas en IA de GPT ahora.",
        search : "Buscar",
        gptSearchBarPlaceHolder : "¿Qué te gustaría ver hoy?",
    },
    fr : {
        headerWelcome: "Bienvenue",
        signIn: "Se connecter",
        signUp: "S'inscrire",
        home: "Accueil",
        signOut: "Se déconnecter",
        name: "Nom",
        email: "Adresse e-mail",
        password: "Mot de passe",
        confirmPassword: "Confirmer le mot de passe",
        offlineheadind01: "Votre système est hors ligne!",
        offlineheadind02: "Veuillez vérifier la connexion Internet.",
        nowPlaying: "En cours de lecture",
        popular: "Populaire",
        topRated: "Les mieux notés",
        upcoming: "À venir",
        play: "Lire",
        gptSearch: "Recherche GPT",
        gptSearchHeadind01: "Laissez GPT être votre génie du cinéma, trouvant le film parfait juste pour vous!",
        gptSearchHeadind02: "Améliorez vos choix de films avec les recommandations basées sur l'IA de GPT maintenant.",
        search: "Recherche",
        gptSearchBarPlaceHolder: "Que voulez-vous regarder aujourd'hui?",
    },
    de : {
        headerWelcome: "Willkommen",
        signIn: "Einloggen",
        signUp: "Anmelden",
        home: "Startseite",
        signOut: "Abmelden",
        name: "Name",
        email: "E-Mail-Adresse",
        password: "Passwort",
        confirmPassword: "Passwort bestätigen",
        offlineheadind01: "Ihr System ist offline!",
        offlineheadind02: "Bitte überprüfen Sie die Internetverbindung.",
        nowPlaying: "Jetzt spielen",
        popular: "Beliebt",
        topRated: "Bestbewertet",
        upcoming: "Bevorstehend",
        play: "Abspielen",
        gptSearch: "GPT-Suche",
        gptSearchHeadind01: "Lassen Sie GPT Ihr Filmgenie sein und den perfekten Film für Sie finden!",
        gptSearchHeadind02: "Optimieren Sie Ihre Filmwahl jetzt mit GPTs KI-gesteuerten Empfehlungen.",
        search: "Suche",
        gptSearchBarPlaceHolder: "Was möchten Sie heute ansehen?",
    },
    it : {
        headerWelcome: "Benvenuto",
        signIn: "Accedi",
        signUp: "Iscriviti",
        home: "Pagina iniziale",
        signOut: "Disconnetti",
        name: "Nome",
        email: "Indirizzo e-mail",
        password: "Password",
        confirmPassword: "Conferma Password",
        offlineheadind01: "Il tuo sistema è offline!",
        offlineheadind02: "Controlla la connessione a Internet.",
        nowPlaying: "Ora in riproduzione",
        popular: "Popolare",
        topRated: "I più votati",
        upcoming: "Prossimamente",
        play: "Gioca",
        gptSearch: "Ricerca GPT",
        gptSearchHeadind01: "Lascia che GPT sia il tuo genio del cinema, trovando il film perfetto solo per te!",
        gptSearchHeadind02: "Potenzia le tue scelte cinematografiche con i consigli basati su IA di GPT ora.",
        search: "Ricerca",
        gptSearchBarPlaceHolder: "Cosa ti piacerebbe guardare oggi?",
    },
    pt : {
        headerWelcome: "Bem-vindo",
        signIn: "Entrar",
        signUp: "Inscrever-se",
        home: "Página inicial",
        signOut: "Sair",
        name: "Nome",
        email: "Endereço de e-mail",
        password: "Senha",
        confirmPassword: "Confirmar Senha",
        offlineheadind01: "Seu sistema está offline!",
        offlineheadind02: "Por favor, verifique a conexão com a Internet.",
        nowPlaying: "Agora tocando",
        popular: "Popular",
        topRated: "Mais bem avaliados",
        upcoming: "Próximos",
        play: "Jogar",
        gptSearch: "Pesquisa GPT",
        gptSearchHeadind01: "Deixe o GPT ser seu gênio do cinema, encontrando o filme perfeito só para você!",
        gptSearchHeadind02: "Aprimore suas escolhas de filmes com as recomendações baseadas em IA do GPT agora.",
        search: "Pesquisa",
        gptSearchBarPlaceHolder: "O que você gostaria de assistir hoje?",
    },
    ru : {
        headerWelcome: "Добро пожаловать",
        signIn: "Войти",
        signUp: "Зареги",
        home: "Главная страница",
        signOut: "Выйти",
        name: "Имя",
        email: "Адрес электронной почты",
        password: "Пароль",
        confirmPassword: "Подтвердите пароль",
        offlineheadind01: "Ваша система офлайн!",
        offlineheadind02: "Пожалуйста, проверьте подключение к Интернету.",
        nowPlaying: "Сейчас играет",
        popular: "Популярные",
        topRated: "Высоко оцененные",
        upcoming: "Ожидаемые",
        play: "Играть",
        gptSearch: "Поиск GPT",
        gptSearchHeadind01: "Пусть GPT станет вашим кино-джинном, находящим идеальный фильм специально для вас!",
        gptSearchHeadind02: "Усилите ваш выбор фильмов с помощью рекомендаций на базе ИИ от GPT прямо сейчас.",
        search: "Поиск",
        gptSearchBarPlaceHolder: "Что вы хотели бы посмотреть сегодня?",
    },
    zhCN : {
        headerWelcome: "欢迎",
        signIn: "登录",
        signUp: "注册",
        home: "主页",
        signOut: "登出",
        name: "姓名",
        email: "电子邮件地址",
        password: "密码",
        confirmPassword: "确认密码",
        offlineheadind01: "您的系统处于离线状态!",
        offlineheadind02: "请检查互联网连接。",
        nowPlaying: "正在播放",
        popular: "受欢迎的",
        topRated: "高评分",
        upcoming: "即将到来",
        play: "播放",
        gptSearch: "GPT搜索",
        gptSearchHeadind01: "让GPT成为您的电影精灵，为您找到完美的电影!",
        gptSearchHeadind02: "立即使用GPT的AI驱动推荐增强您的电影选择。",
        search: "搜索",
        gptSearchBarPlaceHolder: "今天您想看什么？",
    },
    ko : {
        headerWelcome: "환영합니다",
        signIn: "로그인",
        signUp: "가입하기",
        home: "홈페이지",
        signOut: "로그아웃",
        name: "이름",
        email: "이메일 주소",
        password: "비밀번호",
        confirmPassword: "비밀번호 확인",
        offlineheadind01: "시스템이 오프라인 상태입니다!",
        offlineheadind02: "인터넷 연결을 확인하십시오.",
        nowPlaying: "현재 상영 중",
        popular: "인기 있는",
        topRated: "최고 평점",
        upcoming: "곧 개봉",
        play: "재생",
        gptSearch: "GPT 검색",
        gptSearchHeadind01: "GPT가 당신의 영화 진이 되어 완벽한 영화를 찾아드립니다!",
        gptSearchHeadind02: "지금 GPT의 AI 기반 추천으로 영화 선택을 강화하세요.",
        search: "검색",
        gptSearchBarPlaceHolder: "오늘 무엇을 보고 싶으신가요?",
    },
    ar : {
        headerWelcome: "مرحبا",
        signIn: "تسجيل الدخول",
        signUp: "اشتراك",
        home: "الصفحة الرئيسية",
        signOut: "تسجيل الخروج",
        name: "اسم",
        email: "عنوان البريد الإلكتروني",
        password: "كلمه السر",
        confirmPassword: "تأكيد كلمة المرور",
        offlineheadind01: "نظامك غير متصل!",
        offlineheadind02: "يرجى التحقق من اتصال الإنترنت.",
        nowPlaying: "الآن يعرض",
        popular: "شائع",
        topRated: "أعلى تقييم",
        upcoming: "القادمة",
        play: "لعب",
        gptSearch: "بحث GPT",
        gptSearchHeadind01: "دع GPT يكون جني أفلامك، ويكتشف الفيلم المثالي لك فقط!",
        gptSearchHeadind02: "عزز اختيارات أفلامك بتوصيات GPT المدعومة بالذكاء الاصطناعي الآن.",
        search: "بحث",
        gptSearchBarPlaceHolder: "ماذا تريد أن تشاهد اليوم؟",
    },
}

export default lang;